openapi: 3.0.3
info:
  title: LLM学術文書支援システム API
  description: |
    LLM学術文書支援システムのRESTful API仕様です。
    プロジェクト管理、文書処理、LLM連携、学習ノート生成などの機能にアクセスできます。
  version: 1.0.0
  contact:
    name: 開発チーム
    email: dev@example.com

servers:
  - url: https://api.example.com/v1
    description: 本番環境
  - url: https://api-staging.example.com/v1
    description: ステージング環境
  - url: http://localhost:8000/v1
    description: 開発環境

tags:
  - name: 認証
    description: ユーザー認証・認可に関するエンドポイント
  - name: プロジェクト
    description: プロジェクト管理に関するエンドポイント
  - name: 文書
    description: 文書管理と処理に関するエンドポイント
  - name: LLM
    description: LLMとの連携に関するエンドポイント
  - name: ノート
    description: 学習ノート管理に関するエンドポイント
  - name: 検索
    description: 文書・ノートの検索に関するエンドポイント
  - name: ファイル
    description: ファイル管理に関するエンドポイント
  - name: ユーザー
    description: ユーザー管理に関するエンドポイント
  - name: 管理者
    description: 管理者向けエンドポイント

paths:
  /auth/register:
    post:
      tags:
        - 認証
      summary: 新規ユーザー登録
      description: 新しいユーザーアカウントを作成します
      operationId: registerUser
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - email
                - password
                - name
              properties:
                email:
                  type: string
                  format: email
                  example: "user@example.com"
                password:
                  type: string
                  format: password
                  example: "SecurePassword123!"
                name:
                  type: string
                  example: "山田 太郎"
      responses:
        '201':
          description: 登録成功
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  message:
                    type: string
                    example: "ユーザー登録が完了しました"
                  user:
                    $ref: '#/components/schemas/User'
        '400':
          $ref: '#/components/responses/BadRequest'
        '409':
          description: 既存ユーザーエラー
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: false
                  error:
                    type: object
                    properties:
                      code:
                        type: string
                        example: "AUTH_002"
                      message:
                        type: string
                        example: "このメールアドレスは既に登録されています"

# 以下、主要なスキーマ定義
components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    User:
      type: object
      properties:
        id:
          type: string
          example: "507f1f77bcf86cd799439011"
        name:
          type: string
          example: "山田 太郎"
        email:
          type: string
          format: email
          example: "user@example.com"
        role:
          type: string
          enum: [user, admin]
          example: "user"
        createdAt:
          type: string
          format: date-time
          example: "2023-01-01T12:00:00.000Z"
        updatedAt:
          type: string
          format: date-time
          example: "2023-01-01T12:00:00.000Z"
        lastLogin:
          type: string
          format: date-time
          example: "2023-03-10T15:20:00.000Z"
        settings:
          type: object
          properties:
            theme:
              type: string
              enum: [light, dark, system]
              example: "system"
            language:
              type: string
              example: "ja"

# Note: このファイルは主要なAPI仕様と認証に関する定義を含む基本部分です。
# 他のスキーマは別ファイル（03_OpenAPI仕様_モデル.yaml）にあります。
