        userId:
          type: string
          example: "507f1f77bcf86cd799439011"
        projectId:
          type: string
          example: "507f1f77bcf86cd799439012"
        documentId:
          type: string
          example: "507f1f77bcf86cd799439014"
        sectionId:
          type: string
          example: "507f1f77bcf86cd799439015"
        title:
          type: string
          example: "波動関数の意味について質問"
        messages:
          type: array
          items:
            type: object
            properties:
              role:
                type: string
                enum: [user, assistant, system]
                example: "user"
              content:
                type: string
                example: "波動関数の物理的な意味はなんですか？"
              timestamp:
                type: string
                format: date-time
                example: "2023-03-10T15:20:00.000Z"
              model:
                type: string
                example: "claude-3-opus"
              context:
                type: object
                properties:
                  sectionIds:
                    type: array
                    items:
                      type: string
                    example: ["507f1f77bcf86cd799439015", "507f1f77bcf86cd799439018"]
        createdAt:
          type: string
          format: date-time
          example: "2023-03-10T15:20:00.000Z"
        updatedAt:
          type: string
          format: date-time
          example: "2023-03-10T15:25:00.000Z"
        tags:
          type: array
          items:
            type: string
          example: ["波動関数", "解釈", "確率"]

    Note:
      type: object
      properties:
        id:
          type: string
          example: "507f1f77bcf86cd799439019"
        title:
          type: string
          example: "シュレディンガー方程式の要点まとめ"
        userId:
          type: string
          example: "507f1f77bcf86cd799439011"
        projectId:
          type: string
          example: "507f1f77bcf86cd799439012"
        documentId:
          type: string
          example: "507f1f77bcf86cd799439014"
        content:
          type: string
          example: "# シュレディンガー方程式の要点\n\n## 1. 方程式の形式\n\n時間依存シュレディンガー方程式は以下の形で表される：\n\n$$i\\hbar\\frac{\\partial}{\\partial t}\\Psi(\\mathbf{r},t) = \\hat{H}\\Psi(\\mathbf{r},t)$$\n\nここで $\\hat{H}$ はハミルトニアン演算子..."
        format:
          type: string
          enum: [markdown, html]
          example: "markdown"
        sourceSections:
          type: array
          items:
            type: string
          example: ["507f1f77bcf86cd799439015", "507f1f77bcf86cd799439020"]
        isAutoGenerated:
          type: boolean
          example: true
        generationPrompt:
          type: string
          example: "シュレディンガー方程式の要点をまとめたノートを作成してください"
        createdAt:
          type: string
          format: date-time
          example: "2023-03-15T09:40:00.000Z"
        updatedAt:
          type: string
          format: date-time
          example: "2023-03-16T11:20:00.000Z"
        tags:
          type: array
          items:
            type: string
          example: ["要点", "方程式", "量子力学"]

    Concept:
      type: object
      properties:
        id:
          type: string
          example: "507f1f77bcf86cd799439021"
        name:
          type: string
          example: "波動関数"
        projectId:
          type: string
          example: "507f1f77bcf86cd799439012"
        description:
          type: string
          example: "量子力学において、系の状態を完全に記述する複素関数"
        aliases:
          type: array
          items:
            type: string
          example: ["wave function", "Ψ", "psi関数"]
        relatedConcepts:
          type: array
          items:
            type: object
            properties:
              conceptId:
                type: string
                example: "507f1f77bcf86cd799439022"
              name:
                type: string
                example: "確率解釈"
              relationship:
                type: string
                example: "has interpretation"
        occurrences:
          type: array
          items:
            type: object
            properties:
              documentId:
                type: string
                example: "507f1f77bcf86cd799439014"
              sectionId:
                type: string
                example: "507f1f77bcf86cd799439015"
              count:
                type: integer
                example: 23
        definition:
          type: object
          properties:
            short:
              type: string
              example: "量子系の状態を表す複素関数"
            detailed:
              type: string
              example: "波動関数（Ψ）は量子力学において、粒子やシステムの量子状態を完全に記述する複素関数です。その絶対値の2乗は特定の位置で粒子を見つける確率密度を与えます。"
            examples:
              type: array
              items:
                type: string
              example: ["自由粒子の波動関数: $\\Psi(x,t) = Ae^{i(kx-\\omega t)}$"]
        createdAt:
          type: string
          format: date-time
          example: "2023-02-05T10:45:00.000Z"
        updatedAt:
          type: string
          format: date-time
          example: "2023-02-05T10:45:00.000Z"

    Pagination:
      type: object
      properties:
        currentPage:
          type: integer
          example: 1
        totalPages:
          type: integer
          example: 5
        totalItems:
          type: integer
          example: 42
        itemsPerPage:
          type: integer
          example: 10

    Error:
      type: object
      properties:
        success:
          type: boolean
          example: false
        error:
          type: object
          properties:
            code:
              type: string
              example: "DOC_001"
            message:
              type: string
              example: "ドキュメント処理中にエラーが発生しました"
            details:
              type: object
              example: {
                "field": "file",
                "reason": "不正なPDFフォーマットです"
              }

  responses:
    BadRequest:
      description: リクエスト形式エラー
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    
    Unauthorized:
      description: 認証エラー
      content:
        application/json:
          schema:
            type: object
            properties:
              success:
                type: boolean
                example: false
              error:
                type: object
                properties:
                  code:
                    type: string
                    example: "AUTH_001"
                  message:
                    type: string
                    example: "認証に失敗しました。ログインしてください。"
    
    Forbidden:
      description: アクセス権限エラー
      content:
        application/json:
          schema:
            type: object
            properties:
              success:
                type: boolean
                example: false
              error:
                type: object
                properties:
                  code:
                    type: string
                    example: "AUTH_003"
                  message:
                    type: string
                    example: "このリソースにアクセスする権限がありません"
    
    NotFound:
      description: リソースが見つからない
      content:
        application/json:
          schema:
            type: object
            properties:
              success:
                type: boolean
                example: false
              error:
                type: object
                properties:
                  code:
                    type: string
                    example: "RESOURCE_001"
                  message:
                    type: string
                    example: "指定されたリソースが見つかりません"
    
    ServerError:
      description: サーバー内部エラー
      content:
        application/json:
          schema:
            type: object
            properties:
              success:
                type: boolean
                example: false
              error:
                type: object
                properties:
                  code:
                    type: string
                    example: "SERVER_001"
                  message:
                    type: string
                    example: "サーバー内部でエラーが発生しました"