# LLM学術文書支援システム API仕様
# このファイルはOpenAPI仕様を複数のファイルに分割した構成の統合インデックスです

# OpenAPI仕様の各部分のファイル構成:
# - 03_OpenAPI仕様_基本.yaml: API基本情報、サーバー定義、セキュリティスキーム、基本エンドポイント
# - 03_OpenAPI仕様_モデル.yaml: データモデル定義（スキーマ）
# - 03_OpenAPI仕様_拡張.yaml: 追加エンドポイント、標準レスポンス定義

# 参照先ファイル:
# 基本部分: 03_OpenAPI仕様_基本.yaml
# モデル定義: 03_OpenAPI仕様_モデル.yaml
# 拡張部分: 03_OpenAPI仕様_拡張.yaml

# 注意: このファイルは参照用インデックスです。
# 完全なOpenAPI仕様を取得するには上記3ファイルを統合する必要があります。

openapi: 3.0.3
info:
  title: LLM学術文書支援システム API
  description: |
    LLM学術文書支援システムのRESTful API仕様全体の統合インデックスです。
    
    このAPIは以下の主要機能を提供します：
    - ユーザー認証・認可
    - プロジェクト管理
    - 文書処理と解析
    - LLMとの連携と質問応答
    - 学習ノート生成
    - 検索とナビゲーション
    
    完全な仕様は以下のファイルに分割されています：
    1. 03_OpenAPI仕様_基本.yaml: 基本情報、認証、コアエンドポイント
    2. 03_OpenAPI仕様_モデル.yaml: データモデルとスキーマ定義
    3. 03_OpenAPI仕様_拡張.yaml: 追加エンドポイントとレスポンス
  version: 1.0.0
  contact:
    name: 開発チーム
    email: dev@example.com

# 以下はプレースホルダーです。実際の内容は各ファイルを参照してください。
paths: {}
components: 
  schemas: {}
